version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    container_name: restauracja.api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    command: ["dotnet", "watch", "--project", "Api", "run"]

  restauracja.database:
    image: postgres:latest
    container_name: restauracja.database
    environment:
      - POSTGRES_DB=restauracja
      - POSTGRES_USER=restauracja
      - POSTGRES_PASSWORD=restauracja
    ports:
      - "5432:5432"
    volumes:
      - restauracja_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "restauracja"]
      interval: 30s
      retries: 3
      start_period: 30s

  runtrackr-redis:
    image: redis:latest
    container_name: runtrackr.redis
    restart: always
    ports:
      - "6379:6379"

  runtrackr-blob-storage:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: runtrackr.blob-storage
    volumes:
      - ./containers/blob_storage/data:/data
    ports:
      - "10000:10000"
    command: "azurite-blob --blobHost 0.0.0.0 -l /data"

volumes:
  restauracja_data:
